name: Test Sources

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

defaults:
  run:
    shell: bash

jobs:
  cleanup-runs:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'test sources') || contains(github.event.pull_request.labels.*.name, 'test tools') }}
    runs-on: ubuntu-latest
    steps:
    - uses: rokroskar/workflow-run-cleanup-action@master
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  test-sources:
    needs: cleanup-runs
    if: ${{ contains(github.event.pull_request.labels.*.name, 'test sources') }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-10.15]
        include:
          - os: ubuntu-18.04
            DEPENDENCIES_INSTALLATION: "sudo apt -y install clang-format-9"
          - os: ubuntu-20.04
            DEPENDENCIES_INSTALLATION: "sudo apt -y install clang-format-9"
          - os: macos-10.15
            DEPENDENCIES_INSTALLATION: "brew install clang-format cppcheck"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      if: matrix.os == 'ubuntu-20.04' || github.event.pull_request.draft == false
      with:
         submodules: true
    - name: Set up Python 3.8
      if: matrix.os == 'ubuntu-20.04' || github.event.pull_request.draft == false
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: Jimver/cuda-toolkit@v0.2.4
      id: cuda-toolkit
      if: matrix.os == 'ubuntu-20.04' || github.event.pull_request.draft == false
      with:
        cuda: '10.2.89'
    - name: Test CUDA installation
      if: matrix.os == 'ubuntu-20.04' || github.event.pull_request.draft == false
      run: |
        echo "Installed cuda version is: ${{steps.cuda-toolkit.outputs.cuda}}"
        echo "Cuda install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"
        nvcc -V
    - name: Test Sources
      if: matrix.os == 'ubuntu-20.04' || github.event.pull_request.draft == false
      run: |
        ${{ matrix.DEPENDENCIES_INSTALLATION }}
        export OPENDR_HOME=$PWD
        pip install -r tests/requirements.txt
        python -m unittest discover -s tests
    - name: Test API
      if: ${{ matrix.os == 'ubuntu-20.04' && contains(github.event.pull_request.labels.*.name, 'test tools') }}
      run: |
        ${{ matrix.DEPENDENCIES_INSTALLATION }}
        export OPENDR_HOME=$PWD
        export PYTHONPATH=$OPENDR_HOME/src:$PYTHONPATH
        export DISABLE_BCOLZ_AVX2=true
        make install_compilation_dependencies
        make install_runtime_dependencies
        pip install -r tests/sources/requirements.txt
        python -m unittest discover -s tests/sources
